# - include: ruby.yml tags=ruby
# - include: rbenv.yml tags=rbenv
# - include: nginx.yml tags=nginx
- include: rails.yml tags=rails

- name: Install dependencies
  sudo: yes
  yum: pkg={{item}} state=latest
  with_items:
    - git
    - tar
    - gcc
    - make
    - libffi-devel
    - zlib-devel
    - openssl-devel
    - ruby-devel
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel


# gcc ruby-devel libxml2 libxml2-devel libxslt libxslt-devel
