- name: Make Dir For Rails...
  shell: 'mkdir -p {{rails.dir}}'

- name: "change owner and permission rails.dir"
  sudo: true
  file: path={{ rails.dir }} recurse=yes mode=0755 owner=vagrant group=vagrant

# fix slow networking (due to IPv6) on CentOS 6.x
- name: Fix slow networking (due to IPv6)
  lineinfile: dest=/etc/resolv.conf line="options single-request-reopen" state=present insertafter=EOF

# gem module may be good
- name: Install Rails
  command: gem install rails --no-ri --no-rdoc -v 4.0

# - name: add repo for nodejs
#   sudo: true
#   shell: rpm -ivh http://ftp.riken.jp/Linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
#   register: result
#   ignore_errors: True
#
# - name: Install JavaScript runtime
#   sudo: yes
#   yum: name=npm enablerepo=epel state=present


- name: Checking installed version of nodejs
  shell: /usr/bin/test "$({{nodejs_path}}bin/node -v 2> /dev/null)" = {{nodejs_version_tag}}
  register: wanted_version_installed
  ignore_errors: True
  changed_when: "wanted_version_installed.rc == 1"

- name: Download nodejs {{nodejs_version_tag}}
  get_url: url={{nodejs_tarball_url}} dest={{nodejs_tmp_dir}}{{nodejs_file_name}} timeout=120
  when: wanted_version_installed.rc == 1

- name: Verify SHASUM of nodejs {{nodejs_version_tag}}
  shell: curl {{nodejs_shasum_url}} | grep {{nodejs_file_name}} | sha1sum -c chdir={{nodejs_tmp_dir}}
  when: wanted_version_installed.rc == 1

- name: Unpack nodejs {{nodejs_version_tag}}
  command: tar -xvzf {{nodejs_file_name}} chdir={{nodejs_tmp_dir}}
  when: wanted_version_installed.rc == 1

- name: Compile and install nodejs {{nodejs_version_tag}}
  shell: ./configure --prefix={{nodejs_path}} && make && make install chdir={{nodejs_tmp_dir}}{{nodejs_file_tag}}
  sudo: true
  when: wanted_version_installed.rc == 1
